environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  matrix:
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
#    - MSYS2_ARCH: i686
#      MSYSTEM: MINGW32

install:
    - git clone -b 3.22.0 --depth 1 https://gitlab.gnome.org/GNOME/meld
    - git clone -b 41.0 --depth 1 https://github.com/GNOME/adwaita-icon-theme
    - cp -aL adwaita-icon-theme/Adwaita /usr/share/icons
    - set MELD=%CD%\meld
    - set PATH=C:\msys64\%MSYSTEM%\bin;C:\msys64\usr\bin;%PATH%
    - pacman --noconfirm -Syyuu --overwrite '*'
    - taskkill /F /FI "MODULES eq msys-2.0.dll"
    - pacman --noconfirm -Syyuu --overwrite '*'
    - pacman --noconfirm -S --refresh --needed  --overwrite '*' mingw-w64-%MSYS2_ARCH%-python-cx-freeze mingw-w64-%MSYS2_ARCH%-python-gobject mingw-w64-%MSYS2_ARCH%-python-pytest mingw-w64-%MSYS2_ARCH%-python-distro mingw-w64-%MSYS2_ARCH%-python-matplotlib mingw-w64-%MSYS2_ARCH%-python-certifi mingw-w64-%MSYS2_ARCH%-python-psutil mingw-w64-%MSYS2_ARCH%-python-yaml mingw-w64-%MSYS2_ARCH%-gtksourceview4 mingw-w64-%MSYS2_ARCH%-gsettings-desktop-schemas mingw-w64-%MSYS2_ARCH%-diffutils glib2-devel intltool
    - gdk-pixbuf-query-loaders --update-cache

build_script:
    - patch -p0 -R < meld_build_helpers.patch
    - cp -a bin texttestlib setup_win32.py %MELD%
    - cp wininstall/*.ico %MELD%/data/icons
    - cd %MELD%
    - glib-compile-schemas data
    - python3 setup_win32.py bdist_dumb bdist_msi
    - mv dist %APPVEYOR_BUILD_FOLDER%

artifacts:
    - path: dist\*.zip
    - path: dist\*.msi
